### ISSUE TITLE
Connection class looses properties from RheaConnection

### ISSUE THREAD

**Issue by GaikwadPratik** [amqp/rhea-promise#24]
I am trying to import/overwrite code of RPC server/client from `rhea` library. [Here](https://github.com/GaikwadPratik/rhea-promise/commit/9e810776b1bf116dee853d979af131aa5c88187a) is my attempt for that. Any input from your side are most welcome.

While developing, I noticed objects such `Connection`, `Container` from `rhea-promise` which are wrapper over similar object from `rhea` are losing properties and values from original object. 

1. For instance, on https://github.com/GaikwadPratik/rhea-promise/blob/master/lib/rpc.ts#L260 everything from `remote` is missing. Do we have to add it in this library explicitly?
2. I also noticed that in the `Connection` class you are removing all the attached listeners. If I want to run a custom method (https://github.com/GaikwadPratik/rhea-promise/blob/master/lib/rpc.ts#L242), how do I invoke such method or emitted events? This is similar for all other objects such as `Sender`, `Receiver`, etc....
3. Is my best option to overwrite the `prototyped` method such `bind`/`call` from `RpcServer` and `RpcClient` classes to make them promisified instead of callback based? Is there any other alternative available?

This library is really awesome but due to point 1 and 2 above, I am not able to grasp what exactly are you trying here.... I am assuming that you are trying to promisify the `rhea` library in order to avoid `callback` hell!

**Comment by amarzavery** [comment]
While adding type definitions to `rhea`, @grs mentioned that he wanted to delete the rpc client and the rpc server classes. Hence they were removed from the [type definitions PR](https://github.com/amqp/rhea/pull/70#discussion_r189055766).

That is also one of the reasons I did not expose them from rhea-promise.

@grs 
- Can you let us know why you wanted to delete the rpc client and the server implementations? 
- Are there any plans to remove rpc client and rpc server from the library? If no, then can people take a dependency on it (use them in their applications)?

**Comment by grs** [comment]
Yes, I want to remove the rpc module from rhea or replace it with something better.

**Comment by GaikwadPratik** [comment]
Closing this here and tracking at https://github.com/amqp/rhea/issues/169
