### ISSUE TITLE
How does one know when sender.send actually delivered the message to the server

### ISSUE THREAD

**Issue by swilliams-a3digital** [amqp/rhea-promise#45]
In your examples there is this:

const delivery: Delivery = await sender.send(message);

But it looks like send.send() doesn't return a promise and isn't async.  From some experimenting it looks like it resolves successfully before the message is actually delivered, and if your program terminates messages where appear to have been sent are not actually sent.

**Comment by amarzavery** [comment]
That is true @swilliams-a3digital. "rhea" emits different events like "accepted", "rejected", "released", "modified". The promise is resolved only when "accepted" event is raised. It is rejected for the other 3 events. You can take a look at our implementation in [Azure ServiceBus sdk](https://github.com/Azure/azure-sdk-for-js/blob/master/sdk/servicebus/service-bus/src/core/messageSender.ts#L255-L390) where we wrap those events inside a Promise.

**Comment by swilliams-a3digital** [comment]
So if I understand you correctly, if I want to have a synchronous send where I'm waiting to know it was successful all the way to the server, I need to implement something like your "trySend" from the link above.  Basically I need to send and wait for one of the 4 events, or timeout if I don't get one.

**Comment by amarzavery** [comment]
Yes. I am writing a flavor like that, right now and should be done in ~15 mins. Will send a PR shortly

**Comment by swilliams-a3digital** [comment]
Sweet.  Thanks.  I would definitely take advantage of that.
