### ISSUE TITLE
Add support for abort signal for AwaitableSender.send()

### ISSUE THREAD

**Issue by amarzavery** [amqp/rhea-promise#48]
- Add support for abort signal for AwaitableSender.send(). 
- Should this also be enabled for creating/closing a connection, sender, receiver, session?
- Should we be using `@azure/abort-controller` package over here? If yes, then that would mean taking a dependency on something in `@azure` scope for a generic project like this. It may be ok in the end. However, we should see if there are other alternatives before doing that.

**Comment by amarzavery** [comment]
cc @ramya-rao-a

**Comment by ramya-rao-a** [comment]
@bterlson any thoughts on alternatives to @azure/abort-controller as mentioned above? I believe all we need is the `AbortSignalLike` interface

**Comment by ramya-rao-a** [comment]
cc @ShivangiReja

**Comment by bterlson** [comment]
I don't think a dependency on @azure/abort-controller is appropriate here. As you just need the AbortSignalLike interface, I'd say just roll with that. It only needs to be as complete as what you use internally I think (e.g. if you only use onabort, something like `{ onabort(cb: () => void): void }` might be sufficient even...

**Comment by amarzavery** [comment]
That is not true, If you take a look at the usage of abort controller in the EventHubs Sender over [here](https://github.com/Azure/azure-sdk-for-js/blob/master/sdk/eventhub/event-hubs/src/eventHubSender.ts#L468). You will see that we are checking for the `aborted` property. Which means we will have to pretty much re-implement what we have in `@azure/abort-controller` internally in rhea-promise or create a separate package.

@bterlson - How about moving `abort-controller` to https://github.com/ts-common and publish it under the `@ts-common` scope? That is pretty generic. It is open source and any one can use it.

**Comment by bterlson** [comment]
In the example you linked, all you need is the AbortSignalLike type I think (that's what its using anyway)? I'm not sure what would require you to have the whole implementation, can you explain more?

**Comment by ramya-rao-a** [comment]
AbortSignal support is now available in all the async operations in the latest release of 1.1.0!
