### ISSUE TITLE
npmjs documentation malicious link

### ISSUE THREAD

**Issue by simonpayne58** [amqp/rhea-promise#69]
**Describe the bug**
documentation at https://www.npmjs.com/package/rhea-promise includes link to what might be malicious content.

**To Reproduce**
Follow the link to rhea repo.  I have not validated the content as malicious, but clearly does not resolve to github - instead it sends the user to githhub.

**Comment by ramya-rao-a** [comment]
Thanks for reporting @simonpayne58 

This was fixed in #50, and we will be releasing an update to the package soon

**Comment by ramya-rao-a** [comment]
Version 1.1.0 is now released with the fix for this issue in the readme!
