### ISSUE TITLE
Release new version

### ISSUE THREAD

**Issue by GaikwadPratik** [amqp/rhea-promise#74]
with so many changes to `rhea` and `rhea-promise`, can you please release a new version after #68 ? I would request to release a new version simultaneously with core `rhea` library.

**Comment by GaikwadPratik** [comment]
@amarzavery Can you please publish new package?

**Comment by ramya-rao-a** [comment]
@GaikwadPratik Yes definitely. We are planning to make a release once we get https://github.com/amqp/rhea-promise/pull/66 merged.

**Comment by ramya-rao-a** [comment]
Version 1.1.0 is now released!
