### ISSUE TITLE
Unable to understand to implement filters in receivers from the example

### ISSUE THREAD

**Issue by prateek-poker** [amqp/rhea-promise#89]
Hello,

I was using Rabbitmq with a routing key on a listener. Recently we moved to ActiveMQ and are using the rhea-promise library.
We need to filter the received messages on a queue with multiple receivers. After searching the examples, I came across filters in this example :[Receiver with filter](https://github.com/amqp/rhea-promise/blob/master/examples/receive.ts).

I have a payload that I need to filters mentioned below:
`{
"type": "minutes"
}
`

How do I use the filter on the receiver end?

I am using the following logic:
`
source: {
            address: receiverAddress,
            filter: {
                value: {
                    'type': "minutes",
                    "x-match": "all",
                },
                "foo": types.wrap_described({
                    'message.body.type': 'minutes',
                    'x-match': 'all'
                }, 0x468C00000002)
            },
        },
`

I am still receiving the message at the consumer end even if the value of type is not equal to **minutes**
Any help is appreciated.

**Comment by grs** [comment]
What type of filter are you trying to use? apache.org:legacy-amqp-headers-binding:map? That won't work on the message body. The minutes clause isn't a wrapped as a described type so is not a valid filter.

Bigger question is whether RabbitMQ even supports filters?

**Comment by prateek-poker** [comment]
We are using ActiveMQ. 
Can we use anything to replicate the routing key in it ?

**Comment by grs** [comment]
Sorry, I missed where you said you had moved to activemq. I think activemq will support the selector filter so something like:

```
conn.open_receiver({
    source: {
        address: receiverAddress,
        filter: {'jms-selector':amqp_types.wrap_described("type = 'minutes'", 0x468C00000004)}
   }
})
```

However note that this will only work if you set the 'type' as a message property, not a field in the body.

**Comment by grs** [comment]
I would advise getting a protocol trace on the broker (run broker with env var PN_TRACE_FRM=1 for example) and then raise the question with that trace on the activemq user list.

**Comment by grs** [comment]
Also, 0x468C00000002 is the wrong code, it should be 0x468C00000004. Check that first!

**Comment by prateek-poker** [comment]
> Also, 0x468C00000002 is the wrong code, it should be 0x468C00000004. Check that first!

It worked with this. Thank you !!!
Can you please tell what **0x468C00000004** is ? Will it always be a hardcoded value forever ?

**Comment by prateek-poker** [comment]
Thank you !
