### ISSUE TITLE
Release for Rhea 3.X

### ISSUE THREAD

**Issue by woppa684** [amqp/rhea-promise#95]
Rhea 3.0.2 contains a fix that we need. Would it be possible to release a version that includes this version as a dependency?

@chradek How is this process done normally? Master is already at ^3.0.0 for a while now.

**Comment by woppa684** [comment]
@grs Do you know who manages this library? I see mostly reactions from you on issues.

**Comment by grs** [comment]
@ramya-rao-a or @amarzavery ?

**Comment by jeremymeng** [comment]
v3.0.0 has been released.
